{% set name = "pyfai" %}
{% set version = "0.14.1" %}
{% set sha256 = "089dc3301e44bb954cf11fa5b044d2d9fe8905011e90123feec8b088a2152f3f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/silx-kit/pyFAI/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py build install  # [linux]
  script: rm pyFAI/ext/histogram.c & python setup.py build --no-openmp  # [osx]
  skip: True  # [win]

requirements:
  build:
    - python
    - setuptools
    - numpy x.x
    - cython
    - scipy
    - matplotlib
    - fabio
    - h5py

  run:
    - python
    - numpy x.x
    - fabio
    - scipy
    - h5py
    - pillow
    - lxml
    - matplotlib
    - silx

test:
  imports:
    - pyFAI
    - pyFAI.test
    - pyFAI.third_party
    - pyFAI.gui
  commands:
    - pyFAI-calib -h

about:
  home: https://github.com/silx-kit/pyFAI/
  license: GPL-3
  license_file: LICENSES.txt
  summary: 'Python implementation of fast azimuthal integration'

  description: |
    pyFAI is an azimuthal integration library that tries to be fast (as fast
    as C and even more using OpenCL and GPU). It is based on histogramming of
    the 2theta/Q positions of each (center of) pixel weighted by the intensity
    of each pixel, but parallel version uses a SparseMatrix-DenseVector
    multiplication. Neighboring output bins get also a contribution of pixels
    next to the border thanks to pixel splitting. Finally pyFAI provides also
    tools to calibrate the experimental setup using Debye-Scherrer rings of a
    reference compound.
  doc_url: http://pythonhosted.org/pyFAI/
  dev_url: https://github.com/silx-kit/pyFAI/

extra:
  recipe-maintainers:
    - CJ-Wright
    - tacaswell
    - chiahaoliu
