travis:
  secure:
    BINSTAR_TOKEN: GVdBxBezxVEXrmVrfpnIpkTn1Y58GGXg3UaOxT7nkQoQ4OfmVmbq1rIFVqWqd3Qija86gKupyBp0RI4mFuZhhs2F9/hBZwC+0pAHH4nvkE51lT2J19XPbn/OgIrmkb1bex/YlWC0cqWHAPRKTn1vsyDQ7uJ7cZjDe2W2OFLGjkfeEPQj1IqclRr8RzOE4mOwB3Zx+m4M7pJoQWUxmUp25EChTayxb26vkGmyFR4PtczDsf+uNwjNkYmLXeYvXHmxRc/0MmqmoFjTD+V24xa3S5sHTe8hz3q0E8DE+S96p/ckBysTlwj5yO6l40MLAM2C7uWteJi6BuUNA9/h64CB+4dhEW7lnG0wtH3bIODUqfforneldSB0d52INTrcB5ANdNLtGJtosyy5VObprAw9LgQcVpEPS2GD2dDUAF6+O9wDSWc5dmQyCZnykzUZTvw0RnOJicvBRnA3QkyRvDJ+J6YkoUfwW06FyAYy4kw2K/xBM4lBLhnewCF1yPhmGPgU5DixU5Znmk3V5eZ80kAPtH4yH+iDMHK74kxFalJRDYWju6CRRbLY/be2yhO8cyQBiqeQaC6AtM0/FezyW2Eh9jLRLfGIeV0zRF7KKA3f9O++OnXUvYUx86gSLqXlr2wKu24GODhrgITUCee3+cEj70m6+Yk7HioxIeTvelktm6E=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
